services:
  openalgo:
    image: openalgo:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: openalgo-web
    ports:
      - "5100:5000"  # Fixed port mapping for Synology
      - "8775:8775"  # WebSocket port

    # Mount points for Synology
    volumes:
      - /volume1/docker/openalgo/db:/app/db
      - /volume1/docker/openalgo/.env:/app/.env:ro

    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0

    restart: unless-stopped

    # Add proper user mapping for Synology
    user: "${PUID:-1026}:${PGID:-100}"  # Default Synology user/group IDs
